FROM registry.redhat.io/ubi8/ubi:8.6
LABEL description="This is a custom httpd container image"
RUN yum install -y httpd
EXPOSE 80
ENV LogLevel "info"
ADD https://www.soundczech.cz/temp/lorem-ipsum.pdf /var/www/html
COPY ./src/ /var/www/html/
USER apache
ENTRYPOINT ["/usr/sbin/httpd"]
CMD ["-D", "FOREGROUND"]